import { NsPlaylist } from "../library/ws-widget/collection/src/lib/btn-playlist/btn-playlist.model"
import { NsGoal } from "../library/ws-widget/collection/src/lib/btn-goals/btn-goals.model"

export const API_END_POINTS = {
    // login apis
    SEND_OTP: '/apis/public/v8/ssoLogin/otp/sendOtp',
    RESEND_OTP: '/apis/public/v8/ssoLogin/otp/resendOtp',
    USER_LOGIN: '/apis/public/v8/ssoLogin/login',
    USER_SEARCH: '/apis/public/v8/mobileApp/kong/user/v1/search',
    // signup apis
    USER_SIGNUP: `apis/public/v8/emailMobile/signup`,
    AUTO_USER_SIGNUP: `apis/public/v8/appSignUpWithAutoLogin/register`,
    REGISTERUSERWITHMOBILE: `apis/public/v8/emailMobile/registerUserWithMobile`,
    GENERATE_OTP: `apis/public/v8/emailMobile/generateOtp`,
    VALIDATE_OTP: `apis/public/v8/emailMobile/validateOtp`,
    VERIFY_OTP: `apis/public/v8/forgot-password/verifyOtp`,
    RESET_PASSWORD: `apis/public/v8/forgot-password/reset/proxy/password`,
    profilePid: 'apis/proxies/v8/apis/public/v8/mobileApp/kong/user/v2/read',
    AUTO_VALIDATE_OTP:"apis/public/v8/appSignUpWithAutoLogin/validateOtpWithLogin",
    // app version apis
    MOBILE_APP_VERSION: "/apis/public/v8/mobileApp/version",
     // user service apis
    ROLE_WISE_COMPETENCY: '/apis/public/v8/competencyAssets/roleWiseCompetencyData',
    GET_CORUSES: '/apis/public/v8/publicSearch/getCourses',
    // Observation apis
    GET_MENTEE_FOR_MENTOR: '/apis/public/v8/mobileApp/kong/observationmw/v1/mentor/getAllMenteeForMentor',
    GET_OBSERVATION_FOR_MENTEE: '/apis/public/v8/mobileApp/kong/observationmw/v1/mentor/getObservationForMentee',
    SEND_OBSERVATION_OTP: "/apis/public/v8/mobileApp/kong/observationmw/v1/otp/sendOtp",
    RESEND_OBSERVATION_OTP: "/apis/public/v8/mobileApp/kong/observationmw/v1/otp/retry",
    OTP_VERIFICATION: "/apis/public/v8/mobileApp/kong/observationmw/v1/observation/observationOtpVerification",
    GET_OBSERVATION_DETAILS: "/apis/public/v8/mobileApp/kong/observationmw/v1/observation/getobservationDetails",
    ADD_ENITITY_OBSERVATION: "/apis/public/v8/mobileApp/kong/observationmw/v1/observation/addEntityToObservation",
    SUBMIT_OBSERVATION: '/apis/public/v8/mobileApp/kong/observationmw/v1/observation/submitObservation',
    GET_SUBMISSION_RESULT: '/apis/public/v8/mobileApp/kong/observationmw/v1/observation/getObservationSubmissionResult',
    UPDATE_SUBMISSION_AND_COMPETENCY: '/apis/public/v8/mobileApp/kong/observationmw/v1/observation/updateSubmissionandCompetency',
    GET_MENTORS_OBSERVATION: "/apis/public/v8/mobileApp/kong/observationmw/v1/mentor/getMentorMenteeDetailsFiltered",
    GET_MENTOR_OBSERVATION_COUNT: "/apis/public/v8/mobileApp/kong/observationmw/v1/mentor/mentorObservationFilteredCount",
    GET_MENTEE_ATTEMPTS: "/apis/public/v8/mobileApp/kong/observationmw/v1/observation/menteeConsolidatedObservationAttempts",
    ADD_SECHEDULE: "/apis/public/v8/mobileApp/kong/observationmw/v1/scheduler/v1/observation/schedule",
    SEARCH_V6PUBLIC: '/apis/public/v8/publicContent/v1/search',
    SEARCH_V6PUBLIC_GET_COURSES: '/apis/public/v8/ratingsSearch/getCourses',
    COURSE_BATCH_LIST: `/apis/public/v8/mobileApp/kong/course/v1/batch/list`,
    ENROLL_BATCH: `/apis/public/v8/mobileApp/kong/course/v1/enrol`,
    GOOGLE_AUTHENTICATE: `/apis/public/v8/google/callback`,
    LOGIN_USER: `/apis/public/v8/emailMobile/auth`,
    USER_READ_CONTENT: `/apis/public/v8/mobileApp/kong/user/v2/read`,
    COURSE_HIERARCHY: `/apis/public/v8/mobileApp/kong/course/v1/hierarchy`,
    LATEST_HOMEPAGE_COURSE: `/apis/public/v8/homePage/latestCourses`,
    CONTENT_HISTORYV2: `/apis/public/v8/mobileApp/kong/course/v1/content/state/read`,
    // catalog apis
    catalog: '/apis/public/v8/homePage/catalog',
    GET_WHATSUP_CONTENT: '/apis/public/v8/mobileApp/user/getWhatsappConsent',
    UPDATE_WHATSUP_CONTENT: '/apis/public/v8/mobileApp/user/WhatsappConsent',
    SEARCH_V6PUBLIC_GET_COURSES_RECOMENTED: '/apis/public/v8/ratingsSearch/recommendation/publicSearch/getcourse',

    ASSESSMENT_SUBMIT_V2: `/apis/public/v8/mobileApp/submitAssessment`,
    UPDATE_PASSBOOK: `/apis/public/v8/mobileApp/kong/user/v1/passbook`,
    COMPETENCY_ASSESSMENT_SUBMIT_V2: '/apis/public/v8/mobileApp/v1/competencyAssessment/submit',
    UPDATE_ASHA_PROGRESS: '/apis/public/v8/mobileApp/learnerpath',

    MY_LEARNING: `/LA1/apis/public/v8/mobileApp/kong/la/myLearning`,
    TIME_SPENT: `/api/timespent`,
    NSO_PROGRESS: `/api/nsoArtifactsAndCollaborators`,
    USER_PROGRESS: `/api/userprogress`,
    ASSESSMENTS: `/api/assessment`,
    GET_ASSESSMENTS: `/api/v1/assessment`,
    FILTER_LIST: `/api/progressSource`,
    SKILL_DATA: `/api/managerRecommendedSkills`,
    AUTHORING_CONTENT: `/apis/authApi/hierarchy`,


    USER_READ: (userId: string | undefined) => `/apis/public/v8/mobileApp/kong/user/v2/read/${userId}`,
    GET_ASHA_PROGRESS:(userId: string | undefined) => `/apis/public/v8/mobileApp/learnerpath?userId=${userId}`,
    GET_OBSERVATION_LIST_OF_MENTOR: (mentorId: string | undefined) =>`/apis/public/v8/mobileApp/kong/observationmw/v1/observation/getMentorAssignedSolutionsList?mentorId=${mentorId}`,
    GET_ALL_SECHULDES:(mentorId: string | undefined) => `/apis/public/v8/mobileApp/kong/observationmw/v1/scheduler/v1/getScheduledObservationList?mentorId=${mentorId}`,
    GET_ALL_COMPLETED_SCHEDULES:(menteeId: string | undefined) => `/apis/public/v8/mobileApp/kong/observationmw/v1/observation/menteeConsolidatedObservationAttemptsV2?menteeId=${menteeId}&groupBy=solution_id`,
    GET_ATTEMPS_OF_OBSERVATION: (mentorId: string | undefined,solutionId:string | undefined) => `/apis/public/v8/mobileApp/kong/observationmw/v1/observation/menteeConsolidatedObservationAttemptsV2?mentorId=${mentorId}&solutionId=${solutionId}&groupBy=mentee_id`,
    GET_ATTEMPS_OF_MENTEE: (mentorId: string | undefined,menteeId:string | undefined) => `/apis/public/v8/mobileApp/kong/observationmw/v1/observation/menteeConsolidatedObservationAttemptsV2?mentorId=${mentorId}&menteeId=${menteeId}&groupBy=solution_id`,
    GET_ALL_MENTE_SECHULDES:(menteeId: string | undefined) => `/apis/public/v8/mobileApp/kong/observationmw/v1/scheduler/v1/getScheduledObservationList?menteeId=${menteeId}`,
    // content search apis
    FETCH_USER_ENROLLMENT_LIST: (userId: string | undefined) => `/apis/public/v8/mobileApp/kong/course/v1/user/enrollment/list/${userId}?orgdetails=orgName,email&licenseDetails=name,description,url&fields=contentType,topic,name,channel,mimeType,appIcon,gradeLevel,resourceType,identifier,medium,pkgVersion,thumbnail,board,subject,trackable,posterImage,duration,creatorLogo,license&batchDetails=name,endDate,startDate,status,enrollmentType,createdBy,certificates`,
    FETCH_GENERAL_RC_CERTIFICATE:(userId: string | undefined) => `/apis/public/v8/mobileApp/user/enrollment/list/adhocCertificates`,
    COURSE_RECOMENDATION: (profession: string, appId: string) =>`/apis/public/v8/mobileApp/courseRemommendationv2?profession=${profession}&appId=${appId}`,
    COURSE_RECOMMENDATION_CBP: (appId: string) =>`/apis/public/v8/mobileApp/publicSearch/courseRecommendationCbp?appId=${appId}`,
    FETCH_USER_ENROLLMENT_LIST_V1: (userId: string | undefined) =>`/apis/public/v8/mobileApp/kong/course/v1/user/enrollment/list/${userId}?orgdetails=orgName,email&licenseDetails=name,description,url&fields=contentType,topic,name,channel,mimeType,appIcon,gradeLevel,resourceType,identifier,medium,pkgVersion,thumbnail,board,subject,trackable,posterImage,duration,creatorLogo,license,sourceName,cneName,competency,averageRating&batchDetails=name,endDate,startDate,status,enrollmentType,createdBy,certificates,competency`,
    
    FETCH_USER_ENROLLMENT_LIST_V2: (userId: string | undefined, orgdetails: string, licenseDetails: string, fields: string, batchDetails: string) =>`api/course/v1/user/enrollment/list/${userId}?orgdetails=${orgdetails}&licenseDetails=${licenseDetails}&fields=${fields}&batchDetails=${batchDetails}`,
    CONTENT_AUTH_PARENT: (contentId: string, rootOrg: string, org: string) => `/apis/authApi/action/content/parent/hierarchy/${contentId}?rootOrg=${rootOrg}&org=${org}`,

}

export const API_PROXIES_END_POINTS = {
    SCROM_UPDTE_PROGRESS: `/apis/proxies/v8/content-progres`,
    SCROM_FETCH_PROGRESS: `/apis/proxies/v8/read/content-progres`,
    // content hierarchy apis
    BATCH_CREATE: `/apis/proxies/v8/learner/course/v1/batch/create`,
    CONTENT_SEARCH_V6: `/apis/proxies/v8/sunbirdigot/read`,
    NAVIGATOR_COMMONS_DATA: `/apis/proxies/v8/web-hosted/navigator/json/commonsdata.json`,
    NAVIGATOR_LP_DATA: `/apis/proxies/v8/web-hosted/navigator/json/data.json`,
    NAVIGATOR_ROLES_DATA: `/apis/proxies/v8/web-hosted/navigator/json/nsodata.json`,
}

export const API_PROTECTED_END_POINTS = {
    USER_FEEDBACK: `/apis/protected/v8/user/feedback`,
    // content like apis
    USER_CONTENT_LIKE: `/apis/protected/v8/user/content/like`,
    USER_CONTENT_UNLIKE: `/apis/protected/v8/user/content/unlike`,
    USER_CONTENT_LIKES: `/apis/protected/v8/user/content/contentLikes`,
    // user profile apis
    follow: '/apis/protected/v8/user/follow',
    unfollow: '/apis/protected/v8/user/follow/unfollow',
    getFollowing: '/apis/protected/v8/user/follow/getFollowing',
    // content apis
    PROGRESS_HASH: `/apis/protected/v8/user/progress`,
    // content progress apis
    markAsComplete: `/apis/protected/v8/user/realTimeProgress/markAsComplete`,
    USER_SHARE: `/apis/protected/v8/user/share`,
    USER_CONTENT_SHARE: `/apis/protected/v8/user/share/content`,
    // content apis
    CONTENT: `/apis/protected/v8/content`,
    CONTENT_LIKES: `/apis/protected/v8/content/likeCount`,
    SET_S3_COOKIE: `/apis/protected/v8/content/setCookie`,
    SET_S3_IMAGE_COOKIE: `/apis/protected/v8/content/setImageCookie`,
    FETCH_MANIFEST: `/apis/protected/v8/content/getWebModuleManifest`,
    FETCH_WEB_MODULE_FILES: `/apis/protected/v8/content/getWebModuleFiles`,
    MULTIPLE_CONTENT: `/apis/protected/v8/content/multiple`,
    CONTENT_SEARCH_V5: `/apis/protected/v8/content/searchV5`,
    CONTENT_SEARCH_REGION_RECOMMENDATION: `/apis/protected/v8/content/searchRegionRecommendation`,
    CONTENT_HISTORY: `/apis/protected/v8/user/history`,
    USER_CONTINUE_LEARNING: `/apis/protected/v8/user/history/continue`,
    CONTENT_RATING: `/apis/protected/v8/user/rating`,
    REGISTRATION_STATUS: `/apis/protected/v8/admin/userRegistration/checkUserRegistrationContent`,
    updateHierarchy: `/apis/protected/v8/content/hierarchy/update`,
    editKBDetails: `/apis/protected/v8/content/kb`,
    getFollowers: `/apis/protected/v8/user/follow/getFollowers`,
    editKBDetailsV2: `/apis/protected/v8/content/kb/v2`,
    reorderKbV3: `/apis/protected/v8/content/kb/v3/reorder`,
    // playlist apis
    getAllPlaylists: `/apis/protected/v8/user/playlist`,
    deletePlaylist: `/apis/protected/v8/user/playlist`,
    createPlaylist: `/apis/protected/v8/user/playlist`,
    sharePlaylist: '/apis/protected/v8/user/playlist/share',
    createGoal: `/apis/protected/v8/user/goals`,
    getCommonGoals: `/apis/protected/v8/user/goals/common`,
    
    // content assign apis
    assignContent: `/apis/protected/v8/user/content-assign/assignContent`,
    getAdminLevel: `/apis/protected/v8/user/content-assign/getAdminLevel`,
    getAssignments: `/apis/protected/v8/user/content-assign/getAssignments`,
    searchUsers: `/apis/protected/v8/user/content-assign/searchUsers`,
    managerDetails: `/apis/protected/v8/user/details/managerDetails`,
    // user profile apis
    USER_FOLLOW_DATA: `/apis/protected/v8/user/follow/fetchAll`, // #GET
    USER_FOLLOW: `/apis/protected/v8/user/follow`, // #POST
    USER_UNFOLLOW: `/apis/protected/v8/user/follow/unfollow`, // #POST
    // social apis
    SOCIAL_TIMELINE: `/apis/protected/v8/social/post/timeline`,
    SOCIAL_VIEW_CONVERSATION: `/apis/protected/v8/social/post/viewConversation`,
    SOCIAL_VIEW_CONVERSATION_V2: `/apis/protected/v8/social/post/viewConversationV2`,
    SOCIAL_POST_PUBLISH: `/apis/protected/v8/social/post/publish`,
    SOCIAL_POST_DELETE: `/apis/protected/v8/social/post/delete`,
    SOCIAL_POST_ACTIVITY_UPDATE: `/apis/protected/v8/social/post/activity/create`,
    SOCIAL_POST_ACTIVITY_USERS: `/apis/protected/v8/social/post/activity/users`,
    SOCIAL_POST_UPDATE: `/apis/protected/v8/social/edit/meta`,
    CONTENT_PARENTS: `/apis/protected/v8/content/parents`,
    CONTENT_NEXT: `/apis/protected/v8/content/next`,
    // gamification apis
    fetchBoards: `/apis/protected/v8/leaderboard/fetchLeaderBoardDetails`,
    fetchBadges: `/apis/protected/v8/leaderboard/badgeDetails`,
    fetchDealers: `/apis/protected/v8/leaderboard/dealersDetails`,
    fetchBadgesWon: `/apis/protected/v8/leaderboard/badgeWon`,
    fetchBadgesYetToWin: `/apis/protected/v8/leaderboard/badgeYetToWin`,
    fetchUserProfile: `/apis/protected/v8/leaderboard/userDetails`,
    updateApprovedPoints: `/apis/protected/v8/leaderboard/UpdateApprovedPoints`,
    fetchGuildLeaderboard: `/apis/protected/v8/leaderboard/leaderboardGuild`,
    fetchActivityLeaderboard: `/apis/protected/v8/leaderboard/leaderboardActivities`,
    fetchConfigs: `/apis/protected/v8/leaderboard/fetchConfiguration`,
    updateConfigs: `/apis/protected/v8/leaderboard/updateConfiguration`,
    Getsso: `/apis/protected/v8/leaderboard/GetSSO`,
    GetBalance: `/apis/protected/v8/leaderboard/GetBalance`,
    LIVE_EVENTS: `/apis/protected/v8/events`,
    // navigator apis
    NAVIGATOR_LP: `/apis/protected/v8/navigator/lp`,
    NAVIGATOR_FS: `/apis/protected/v8/navigator/fp`,
    NAVIGATOR_ROLES: `/apis/protected/v8/navigator/roles`,
    NAVIGATOR_ROLE: `/apis/protected/v8/navigator/role`,
    NAVIGATOR_SUGGESTIONS: `/apis/protected/v8/navigator/topics`,
    NAVIGATOR_BPM_DATA: `/apis/protected/v8/navigator/bpm`,
    lexPlatform: `/apis/protected/v8/counter`,
    infyMeCounter: `/apis/protected/v8/counter/infyMe`,
    EMAIL_TEXT: `/apis/protected/v8/user/email/emailText`, // #POST
    FETCH_TO_DOS: `/apis/protected/v8/user/ocm/getToDos`,
    userTopics: `/apis/protected/v8/user/topics`,
    lastlearnt: `/apis/protected/v8/user/history`,
    getFollowersv3: `/apis/protected/v8/user/follow/getFollowersv3`,
    getFollowingv3: `/apis/protected/v8/user/follow/getFollowingv3`,
    getDetails: `/apis/protected/v8/user/details/detailV2`,
    USER_BADGE: `/apis/protected/v8/user/badge`,
    USER_BADGE_RECENT: `/apis/protected/v8/user/badge/notification`,
    USER_BADGES_UPDATE: `/apis/protected/v8/user/badge/update`,
    GENERATE_QRCODE: `/apis/protected/v8/generateQRCode`,
    recommendedTopics: `/apis/protected/v8/user/topic/recommend`,
    addMultiple: `/apis/protected/v8/user/topics/addMultiple`,
    suggestedTopics: `/apis/protected/v8/user/topics/suggested`,
    autocompleteTopics: `/apis/protected/v8/user/topics/autocomplete`,
    NOTIFICATIONS: `/apis/protected/v8/user/notifications/settings`,
    USER_ORG_GRAPH: `/apis/protected/v8/user/dashboard/userOrgTime`,
    SOCIAL_VIEW_SEARCH_RESULT: `/apis/protected/v8/social/post/search`,
    SEARCH_V6: `/apis/protected/v8/content/searchV6`,
    SOCIAL_MODERATOR_TIMELINE: `/apis/protected/v8/social/moderator/timeline`,
    SOCIAL_FORUMVIEW: `/apis/protected/v8/social/forum/forumTimeline`,
    SOCIAL_ADMIN_TIMELINE: `/apis/protected/v8/social/admin/timeline`,
    SOCIAL_FORUM_BY_ID: `/apis/protected/v8/social/viewForum`,
    SOCIAL_ADMIN_DEL: `/apis/protected/v8/social/admin/deletePost`,
    SOCIAL_ADMIN_REVIVE: `/apis/protected/v8/social/admin/reactivatePost`,
    USER_CONTENT_FLAG: `/apis/protected/v8/social/post/activity/create`,
    SOCIAL_MODERATOR_REACT: `/apis/protected/v8/social/moderator/moderatepost`,
    SOCIAL_POST_DRAFT: `/apis/protected/v8/social/post/draft`,
    SOCIAL_POST_AUTOCOMPLETE: `/apis/protected/v8/social/post/autocomplete?pgno=0&pgsize=10`,
    SOCIAL_POST_ACCEPT_ANSWER: `/apis/protected/v8/social/post/acceptAnswer`,
    CATALOG_AUTHORING: `/apis/protected/v8/social/catalog`,
    SCROM_ADD_UPDTE: '/apis/protected/v8/scrom/add',
    SCROM_FETCH: '/apis/protected/v8/scrom/get',
    INITIALIZE_DB: `/apis/protected/v8/user/rdbms/initializeDb`,
    EXECUTE: `/apis/protected/v8/user/rdbms/executeQuery`,
    CONCEPT_DATA: `/apis/protected/v8/user/rdbms/conceptData`,
    COMPOSITE: `/apis/protected/v8/user/rdbms/compositeQuery`,
    EXPECTED_OUTPUT: `/apis/protected/v8/user/rdbms/expectedOutput`,
    VERIFY: `/apis/protected/v8/user/rdbms/verifyExercise`,
    SUBMIT: `/apis/protected/v8/user/rdbms/submitExercise`,
    DB_STRUCTURE: `/apis/protected/v8/user/rdbms/dbStructure`,
    TABLE_REFRESH: `/apis/protected/v8/user/rdbms/tableRefresh`,
    PLAYGROUND: `/apis/protected/v8/user/rdbms/playground`,
    COMPARE_QUERY: `/apis/protected/v8/user/rdbms/compareQuery`,
    PROGRESS: `/apis/protected/v8/user/dashboard/course`,
    PROGRESS_CHILDREN: `/apis/protected/v8/user/dashboard/course/details`,
    USER_CERTIFICATION: `/apis/protected/v8/user/certification`,
    
    removeContentFromGoal: (goalId: string, contentId: string, goalType: string) =>`/apis/protected/v8/user/goals/removeContent/${goalId}/${contentId}?goal_type=${goalType}`,
    AUTOCOMPLETE: (query: string) => `/apis/protected/v8/user/autocomplete/${query}`,
    following: (type: string) => `/apis/protected/v8/user/follow/${type}`,
    COLLECTION_HIERARCHY: (type: string, id: string) =>`/apis/protected/v8/content/collection/${type}/${id}`,
    MARK_AS_COMPLETE_META: (contentId: string) => `/apis/protected/v8/user/progress/${contentId}`,
    FETCH_USER_GROUPS: (userId: string) =>`/apis/protected/v8/user/group/fetchUserGroup?userId=${userId}`,
    acceptRejectGoal: (action: string, goalType: string, goalId: string, confirm: boolean) =>`/apis/protected/v8/user/goals/action/${action}/${goalType}/${goalId}?confirm=${confirm}`,
    deleteGoal: (type: string, id: string) => `/apis/protected/v8/user/goals/${type}/${id}`,
    deleteGoalForUsers: (type: string, id: string) => `/apis/protected/v8/user/goals/removeUsers/${type}/${id}`,
    getActionRequiredGoals: (sourceFields: string) =>`/apis/protected/v8/user/goals/action?sourceFields=${sourceFields}`,
    getUserGoals: (type: NsGoal.EGoalTypes, sourceFields: string) =>`/apis/protected/v8/user/goals/${type}?sourceFields=${sourceFields}`,
    getOthersGoals: (sourceFields: string) =>`/apis/protected/v8/user/goals/for-others?sourceFields=${sourceFields}`,
    trackGoal: (id: string, type: NsGoal.EGoalTypes) =>`/apis/protected/v8/user/goals/track/${type}/${id}`,
    shareGoal: (type: string, id: string) => `/apis/protected/v8/user/goals/share/${type}/${id}`,
    shareGoalV2: (type: string, id: string) => `/apis/protected/v8/user/goals/share/${type}/${id}`,
    updateDurationCommonGoal: (type: string, id: string, duration: number) =>`/apis/protected/v8/user/goals/updateDurationCommonGoal/${type}/${id}?duration=${duration}`,
    addContentToGoal: (goalId: string, contentId: string, goalType: string) =>`/apis/protected/v8/user/goals/addContent/${goalId}/${contentId}?goal_type=${goalType}`,
    playlist: (type: NsPlaylist.EPlaylistTypes) => `/apis/protected/v8/user/playlist/${type}`,
    upsertPlaylist: (playlistId: string) => `/apis/protected/v8/user/playlist/${playlistId}`,
    acceptPlaylist: (playlistId: string) => `/apis/protected/v8/user/playlist/accept/${playlistId}`,
    rejectPlaylist: (playlistId: string) => `/apis/protected/v8/user/playlist/reject/${playlistId}`,
    updatePlaylists: (playlistId: string) => `/apis/protected/v8/user/playlist/${playlistId}`,
    CONTENT_PARENT: (contentId: string) => `/apis/protected/v8/content/${contentId}/parent`,
    EXTERNAL_CONTENT: (contentId: string) =>`/apis/protected/v8/content/external-access/${contentId}`,
    RELATED_RESOURCE: (contentId: string, contentType: string) =>`/apis/protected/v8/khub/fetchRelatedResources/${contentId}/${contentType}`,
    POST_ASSESSMENT: (contentId: string) => `/apis/protected/v8/user/evaluate/post-assessment/${contentId}`,
    getUserProfileGoals: (type: NsGoal.EGoalTypes, sourceFields: string, wid: string) =>`/apis/protected/v8/user/goals/${type}?sourceFields=${sourceFields}&wid=${wid}`,
    translateFilters: (lang: string) => `/apis/protected/v8/translate/filterdata/${lang}`,
}

export const API_END_POINTS_S3 = {
    ORG_DATA: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/ekshamataOrgConfig.json`,
    COMPETENCY_ORG_DATA: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/learnerPath.config.json?v=${new Date().getTime()}`,
    STATIC_CONTENT: 'https://aastar-app-assets.s3.ap-south-1.amazonaws.com/sphere-home-content.json',
}

